#!/bin/bash -eu

# Prompt for the title
read -p "Enter the title: " title

# Get today's date
date=$(date +"%Y-%m-%d")

# Define the file path
file_path="_posts/${title}.md"

# Create the new markdown file with front matter
cat <<EOL > $file_path
---
title: "${title}"
date: ${date}
---

EOL

echo "New post created at $file_path"
vim +$ $file_path
